version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT_OUT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "${REDIS_PORT_OUT}:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    environment:
      PORT: ${BACKEND_PORT}
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
    command: air

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:${BACKEND_PORT}
    command: npm run dev -- --host 0.0.0.0

volumes:
  db_data:
  redis_data:
